name: collection_creator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  change_notifier: ^0.28.0
  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"